//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenderComp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompony
    {
        public int ID { get; set; }
        public string ComponyName { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<bool> IsAccept { get; set; }
        public Nullable<double> X { get; set; }
        public string Comment { get; set; }
        public Nullable<double> t { get; set; }
        public Nullable<double> L { get; set; }
        public Nullable<double> IeDiff { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> TenderID { get; set; }
        public Nullable<bool> IsWin { get; set; }
        public Nullable<double> CurrencyPrice { get; set; }
        public Nullable<double> RialiPrice { get; set; }
    
        public virtual tblTender tblTender { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
