//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenderComp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTender
    {
        public tblTender()
        {
            this.tblComponies = new HashSet<tblCompony>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TenderNo { get; set; }
        public Nullable<bool> TenderType { get; set; }
        public Nullable<int> Currency { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<double> t { get; set; }
        public Nullable<double> Estimate { get; set; }
        public Nullable<double> Fguaranty { get; set; }
        public Nullable<double> i { get; set; }
        public Nullable<System.DateTime> TenderDate { get; set; }
        public Nullable<double> CurrencyPrice { get; set; }
        public Nullable<double> Quorum { get; set; }
        public Nullable<double> Average { get; set; }
        public Nullable<double> Variance { get; set; }
        public Nullable<double> UpperLimit { get; set; }
        public Nullable<double> BottomLimit { get; set; }
        public string TenderName { get; set; }
        public Nullable<double> CurrencyEstimate { get; set; }
        public Nullable<double> RialiEstimate { get; set; }
        public Nullable<double> Average2 { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual ICollection<tblCompony> tblComponies { get; set; }
    }
}
