//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TenderComp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public tblUser()
        {
            this.tblTenders = new HashSet<tblTender>();
            this.tblComponies = new HashSet<tblCompony>();
        }
    
        public int ID { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string username { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<tblTender> tblTenders { get; set; }
        public virtual ICollection<tblCompony> tblComponies { get; set; }
    }
}
